name: WakaTime Stats

on:
  schedule:
    # Schedule updates for once every day (change cron as needed)
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WakaTime Statistics
        uses: athul/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: set to true if you want to show more details
          SHOW_OS: true
          SHOW_PROJECTS: true
