name: WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WakaTime Statistics
        uses: athul/waka-readme@main
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Additional configuration for WakaTime stats
          SHOW_OS: true
          SHOW_PROJECTS: true
